version: '3.8'

services:
  vault:
    image: hashicorp/vault
    container_name: Vault
    volumes:
      - vault_data:/vault/data
      - ./scripts/init-vault.sh:/vault/config/init-vault.sh
      - ./scripts/vault-config.hcl:/vault/config/vault-config.hcl
    ports:
      - "8200:8200"
    command:
      - "server"
    cap_add:
      - IPC_LOCK

  web:
    container_name: Django
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
      - vault
    environment:
      VAULT_ADDR: http://vault:8200
    entrypoint: ["/bin/sh", "-c", "/app/entrypoint.sh"]

  db:
    container_name: Postgres_prod
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/entrypoint-db.sh:/app/entrypoint-db.sh
    depends_on:
      - vault
    environment:
      VAULT_ADDR: http://vault:8200
    entrypoint: ["/bin/sh", "-c", "/app/entrypoint-db.sh"]

volumes:
  postgres_data:
  vault_data:
