version: '3.8'

services:
  web:
    container_name: Django
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app  # Allows changes in real time
    depends_on:
      - db

  db:
    container_name: Postgres
    image: postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
